language: python

dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
before_install:
  - nvm install node
install:
  - pip install -r requirements-dev.txt
  - python setup.py build
script:
  - pytest test
